language: rust
rust:
  - nightly
  - beta
  - stable
script:
  - cargo build
  - cargo doc
  - cargo test
  - "(cd capi/ctest; ./build-and-test.sh)"
after_success: curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
notifications:
  webhooks: http://build.servo.org:54856/travis
